### PR TITLE
feat: add support for other fluids and air

### LINKED ISSUE #13: Add support for other fluids
**Is your feature request related to a problem? Please describe.**
The Universal mopeka sensor supports multiple fluid types. The current output is in mm of propane which is an inaccurate reading for other fluid types. It loses precision when converting to an int.

**Describe the solution you'd like**
A drop down for each sensor to describe the fluid it is sensing. You can find the coefficients for other fluids here: https://gist.github.com/dirkjanfaber/2a3238f041310d44af030bf1bdb5e5ad

Provide the tank_level reading as a float instead of an int.

Provide the raw sensor reading. tank_level_raw

Remove the quality requirement for publication or lower it.

### PR DESCRIPTION
**Pull request by cayossarian**
closes #13 

```
   AIR
   FRESH_WATER
   WASTE_WATER
   LIVE_WELL
   BLACK_WATER
   RAW_WATER 
   GASOLINE
   DIESEL
   LNG
   OIL
   HYDRAULIC_OIL
```
Tested with TDR40 top down sensor for air (water tank) and tests added accordingly.  Corresponding issue will be opened in HA core with the associated pull request there.

### CODE REVIEW

**Review by bdraco — APPROVED** [review]
Thanks @cayossarian

**Comment by bdraco** [comment]
0.8.0 published

**Comment by bdraco** [comment]
Also in HA, please implement as a config entry options flow

**Comment by chadroad** [comment]
With these new Mopeka updates is there a way to have HA display the reading in percentage instead of inches please?  

The Mopkea app allows you to change them, but not in HA. If not can you please provide some sample code that would make this work? 

I am using the Pro-H20 sensors on RV water tanks but they are different sizes. One is 8" in height and the other is 6". Those inch readings have to be specified inside the Mopeka app for each tank. Both are 30 gal tanks, but their physical size dimensions are different. Any help you could give would be greatly appreciated.

**Comment by cayossarian** [comment]
Hi @chadroad Let's take this discussion to the [community board](https://community.home-assistant.io/t/add-tank-percentage-to-mopeka-integration/531322/17) so you can hear from others as well.  I'll post a reply there.

**Pull request merged**
