### PR TITLE
feat: adding the new 2023 "Pro Check Universal" device (M1017020A)

### PR DESCRIPTION
**Pull request by coffeehorn**
Home Assistant Mopeka Integration fails to recognize the new 2023 Pro Check Universal device (see [this issue](https://github.com/home-assistant/core/issues/98323))

### CODE REVIEW

**Review by bdraco — APPROVED** [review]
Thanks @coffeehorn 
CI will release this shortly

**Comment by ak68-hub** [comment]
It seems to be released already with Homeassistant-Dec 2023 Update.
But it doesn´t work: HA can´t find the Mopeka Universal Pro sensors in the Mopeka Integration.
Who got it to run ?

Fortunately the Victron Venus OS Update from 24/1/24 acceps the sensor NOW and it does work perfectly with a modbus-connection.

**Comment by ak68-hub** [comment]
I´ve tried it  again with VenusOS 3.30 to abb the Mopeka-Integration:
with the result: "No devices found"

At a Cerbo GX all Mopeka Universal-Pro devices are found correctly :)

**Comment by tispokes** [comment]
Same on 2024.10.2

**Pull request merged**
